name: CI for Merge on master/main

on:
  push:
    tags:
      - v*
    branches: [ master, main ]

jobs:
  golangci-lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

  build-push:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: Build
      run: go build -o bin/MongoSync

    - name: Push
      uses: actions/upload-artifact@v2
      if: success()
      with:
        name: MongoSync
        path: bin/MongoSync
